aws_region = "ap-south-1"
vpc_name = "my-vpc"
cidr_block = "10.0.0.0/16"
public_subnets_cidr = [ "10.0.1.0/24", "10.0.2.0/24" ]
private_subnets_cidr = [ "10.0.51.0/24", "10.0.52.0/24" ]
igw_name = "my-vpc-igw"
public_route_table_name = "my-vpc-public-route-table"
private_route_table_name = "my-vpc-private-route-table"
nat_gateway_name = "my-vpc-nat-gateway"
instance_type = "t3.micro"
eks_cluster_name = "my-eks-cluster"
eks_version = "1.34"
worker_node_ami_type = "AL2023_x86_64_STANDARD"
worker_node_instance_types = [ "t3.medium" ]