apiVersion: v1
kind: Pod
metadata:
  name: pod-with-empty-dir-volume
  labels:
    volumeType: "emptyDir"
spec:
  volumes:
    - name: empty-dir-volume
      emptyDir: {}
  containers:
    - name: writer-container
      image: busybox
      command:
        ["sh", "-c", "while true; do date >> /tmp/data.txt; sleep 5; done"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      ports:
        - containerPort: 8081
      volumeMounts:
        - name: empty-dir-volume
          mountPath: /tmp

    - name: nginx-container-2
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      ports:
        - containerPort: 8082
      volumeMounts:
        - name: empty-dir-volume
          mountPath: /tmp
          readOnly: true
